name: Cloudflare - .GOVology Deploy (not working yet - needs to be updated for Pagesgo)
## https://github.com/cloudflare/wrangler-action

on:
  workflow_dispatch:
  push:
    branches:
        - publish ## Placeholder for now, so we don't deploy the worker on every commit to main

concurrency:
  group: govology.deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy - Cloudflare
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # - name: Publish Cloudflare Pages [Deprecated]
        # uses: cloudflare/pages-action@v1
        # with: ## https://developers.cloudflare.com/pages/how-to/use-direct-upload-with-continuous-integration/
        #  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        #  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        #  projectName: YOUR_PROJECT_NAME # e.g. 'my-project'
        #  directory: YOUR_DIRECTORY_OF_STATIC_ASSETS # e.g. 'dist'
        #  gitHubToken: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Publish Cloudflare Pages [New] # https://github.com/marketplace/actions/github-action-for-cloudflare-pages
        id: deploy-page
        uses: cloudflare/wrangler-action@v3
        env:
          projectName: "gov0logy"
          projectDir: "periodic-table"
        with: ## https://github.com/cloudflare/wrangler-action?tab=readme-ov-file#deploy-your-pages-site-production--preview
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}  
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}   ## Maybe should be called cloudflare-api-token
          command: |
            pages project list 
            pages deploy ${projectDir} --project-name=${projectName}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          
      - name: print wrangler command output
        env:
          CMD_OUTPUT: ${{ steps.deploy-page.outputs.command-output }}
        run: echo $CMD_OUTPUT

      - name: Deploy Cloudflare Worker
        id: deploy-worker
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}  
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}   ## Maybe should be called cloudflare-api-token
          workingDirectory: "survey-worker"
          preCommands: |
            echo "*** pre commandS ***"
            echo `pwd`
            npx wrangler --version
            npm install wrangler@latest
            npm install
            echo "******"
          postCommands: |
            echo "*** post commands ***"
            cat /home/runner/.config/.wrangler/logs/*.log
            echo "******"