name: Cloudflare - .GOVology Deploy (not working yet - needs to be updated for Pages)
## https://github.com/cloudflare/wrangler-action

on:
  workflow_dispatch:
  push:
    branches:
        - publish ## Placeholder for now, so we don't deploy the worker on every commit to main

concurrency:
  group: govology.deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    defaults:
      run:
        working-directory: govology-api
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
